"""
Citation mapping for Omniscape_MP_ORIGINAL_BACKUP.odt
Ref number → (scannable_cite, zotero_key)
Generated by searching Zotero library against the reference list.
"""

# Format: ref_num → scannable_cite string
CITATIONS = {
    1:   "{  | Do & Jung, (2018) |  |  |zu:0:I3X5633M}",
    2:   "{  | Menon et al., (2020) |  |  |zu:0:GZD5WNF4}",
    # 3 = DHS website — not in Zotero
    4:   "{  | Blanchi et al., (2018) |  |  |zu:0:SYW6ICMC}",
    # 5 = climate.org website — not in Zotero
    6:   "{  | Wong et al., (2020) |  |  |zu:0:FIFI2IKN}",
    # 7 = statista website — not in Zotero
    8:   "{  | Cova et al., (2013) |  |  |zu:0:5TZR7Z5M}",
    # 9 = Meyer et al. (2012) AASHTO report — not found in Zotero
    10:  "{  | Rivera-Royero et al., (2022) |  |  |zu:0:2AYZAZIF}",
    # 11 = Jaller et al. (2015) Medellin — not found in Zotero
    12:  "{  | Cantillo et al., (2019) |  |  |zu:0:6XY694B2}",
    13:  "{  | Derrible & Kennedy, (2011) |  |  |zu:0:8G6W8E2Z}",
    14:  "{  | Jenelius, (2009) |  |  |zu:0:VBH5H28N}",
    15:  "{  | Boeing, (2019) |  |  |zu:0:AKKCDY4E}",
    16:  "{  | Faturechi & Miller-Hooks, (2014) |  |  |zu:0:6Z3KHEYN}",
    17:  "{  | Zhou et al., (2017) |  |  |zu:0:I8BUU9VR}",
    18:  "{  | Nelson et al., (2019) |  |  |zu:0:7ZJ97BUH}",
    19:  "{  | Grubesic et al., (2008) |  |  |zu:0:466JWVGC}",
    20:  "{  | Taylor et al., (2006) |  |  |zu:0:H93DHSU7}",
    21:  "{  | Casali & Heinimann, (2019) |  |  |zu:0:XYBQPDDM}",  # topological analysis of growth
    22:  "{  | Zhang et al., (2015) |  |  |zu:0:J5QC3RBI}",
    23:  "{  | Ip & Wang, (2009) |  |  |zu:0:2PYRTK7K}",
    24:  "{  | Casali & Heinimann, (2019) |  |  |zu:0:8PVFAMPZ}",  # topological characterization of flooding
    25:  "{  | Zhang & Alipour, (2019) |  |  |zu:0:RH7TPGCN}",
    26:  "{  | Altay & Green, (2006) |  |  |zu:0:GT5LVSLH}",
    27:  "{  | Maspero & Ittmann, (2008) |  |  |zu:0:3CX89H4H}",
    28:  "{  | Rawls & Turnquist, (2010) |  |  |zu:0:YEA4HS5P}",
    29:  "{  | Galindo & Batta, (2013) |  |  |zu:0:LUJ4VBLX}",   # review
    30:  "{  | Galindo & Batta, (2013) |  |  |zu:0:RKKMBQBN}",   # prepositioning
    31:  "{  | Rivera-Royero et al., (2016) |  |  |zu:0:73335M5G}",
    32:  "{  | Rivera-Royero et al., (2020) |  |  |zu:0:3KPZF6W4}",
    33:  "{  | Cova et al., (2011) |  |  |zu:0:E86E2B59}",
    34:  "{  | Grajdura et al., (2021) |  |  |zu:0:FSFMJHW5}",
    35:  "{  | Irsyad & Hitoshi, (2022) |  |  |zu:0:KSUAD4RA}",
    36:  "{  | Bayram, (2016) |  |  |zu:0:9UBVJPL3}",
    37:  "{  | Murray-Tuite & Wolshon, (2013) |  |  |zu:0:WX4NXCI9}",
    38:  "{  | Zhao & Wong, (2021) |  |  |zu:0:UCBZRNRV}",
    39:  "{  | Xie et al., (2010) |  |  |zu:0:KJRRGA3G}",
    40:  "{  | Nassir et al., (2014) |  |  |zu:0:PGRSLTUA}",
    41:  "{  | Shahparvari et al., (2015) |  |  |zu:0:A56T2IKA}",
    42:  "{  | Liang et al., (2023) |  |  |zu:0:C46V23E6}",
    43:  "{  | Khan et al., (2023) |  |  |zu:0:BMEN2INT}",
    44:  "{  | Albahri et al., (2024) |  |  |zu:0:U5QLQ4M9}",
    # 45 = Damasevicuis et al. (2023) IoES — not found in Zotero
    46:  "{  | Lu et al., (2005) |  |  |zu:0:NBT5IED4}",
    47:  "{  | Osman & Ram, (2011) |  |  |zu:0:8PNB2935}",
    48:  "{  | Rungta et al., (2012) |  |  |zu:0:6VFDD6IK}",
    49:  "{  | Zheng et al., (2010) |  |  |zu:0:UIVUTP5B}",
    50:  "{  | Siam et al., (2022) |  |  |zu:0:CACH8G2P}",
    51:  "{  | Lim et al., (2012) |  |  |zu:0:6XYKGZET}",
    52:  "{  | Sheffi et al., (1982) |  |  |zu:0:DUK4NKIS}",
    53:  "{  | Tweedie et al., (1986) |  |  |zu:0:HJ6A2W72}",
    # 54 = Stern & Sinuany-Stern (1989) — not found in Zotero
    55:  "{  | Sherali et al., (1991) |  |  |zu:0:T5WT8IW5}",
    56:  "{  | Church & Cova, (2000) |  |  |zu:0:ESA33L5X}",
    57:  "{  | Cova & Johnson, (2002) |  |  |zu:0:6N384YSR}",
    58:  "{  | Kongsomsaksakul et al., (2005) |  |  |zu:0:SN94TX8N}",
    59:  "{  | Sbayti & Mahmassani, (2006) |  |  |zu:0:ZTSKQQU4}",
    60:  "{  | Han et al., (2006) |  |  |zu:0:4F9ICG2U}",
    61:  "{  | Wolshon & Marchive III, (2007) |  |  |zu:0:8ZSRH2KA}",
    62:  "{  | Chiu et al., (2007) |  |  |zu:0:RGHGG3TU}",
    63:  "{  | Chiu & Zheng, (2007) |  |  |zu:0:CDV2VNAZ}",
    64:  "{  | Miller-Hooks & Sorrel, (2008) |  |  |zu:0:G3IQ2WEL}",
    65:  "{  | Lindell, (2008) |  |  |zu:0:KB9GZ8MS}",
    66:  "{  | Opasanon & Miller-Hooks, (2009) |  |  |zu:0:4RZGIQ3L}",
    67:  "{  | Stepanov & Smith, (2009) |  |  |zu:0:TWW25FKJ}",
    68:  "{  | Noh et al., (2009) |  |  |zu:0:L7MFQ28N}",
    # 69 = Alcada-Almeida et al. (2009) — not found in Zotero
    70:  "{  | Abdelgawad et al., (2010) |  |  |zu:0:I8A4PL36}",
    71:  "{  | Yazici & Ozbay, (2010) |  |  |zu:0:SNUI765F}",
    72:  "{  | Ng et al., (2010) |  |  |zu:0:56ABW3I9}",
    73:  "{  | Ng & Waller, (2010) |  |  |zu:0:PUQX8QDK}",
    # 74 = Lammel et al. (2010) — not found in Zotero
    75:  "{  | Ozbay et al., (2012) |  |  |zu:0:N7NVIGDU}",
    76:  "{  | Li et al., (2012) |  |  |zu:0:F5F4EYB7}",
    # 77 = Coutinho-Rodrigues et al. (2012) — not found in Zotero
    78:  "{  | Chen & Zhan, (2014) |  |  |zu:0:WIVFG3LY}",
    79:  "{  | Lim et al., (2015) |  |  |zu:0:32BJTBSA}",
    80:  "{  | Tuydes-Yaman & Ziliaskopoulos, (2014) |  |  |zu:0:YLV2ARWV}",
    81:  "{  | Bayram et al., (2015) |  |  |zu:0:MVAZV7US}",
    82:  "{  | Shahparvari et al., (2015) |  |  |zu:0:A56T2IKA}",  # same key as 41
    83:  "{  | Gan et al., (2016) |  |  |zu:0:BVF58E8R}",
    84:  "{  | Beloglazov et al., (2016) |  |  |zu:0:TW8T8LP2}",
    85:  "{  | Steer et al., (2017) |  |  |zu:0:QZW586EQ}",
    86:  "{  | Shahabi & Wilson, (2018) |  |  |zu:0:XVT483FB}",
    87:  "{  | Shahparvari et al., (2019) |  |  |zu:0:42YSI3CT}",
    88:  "{  | Grajdura et al., (2022) |  |  |zu:0:4ZKPTLX3}",
    # 89 = McRae et al. (2016) Omniscape — grey lit report, not found in Zotero
    # 90 = McRae et al. (2013) Circuitscape — not found in Zotero
    91:  "{  | Keeley et al., (2018) |  |  |zu:0:RMUWX7JM}",
    # 92 = Schloss et al. (2022) — not found in Zotero
    93:  "{  | Littlefield et al., (2017) |  |  |zu:0:YL28VPHV}",
    # 94 = Littlefield et al. (2019) — not found in Zotero
    95:  "{  | Thorne et al., (2020) |  |  |zu:0:SXGBTUQV}",
    # 96 = California State Geoportal (website)
    # 97 = FEMA NRI Map (website)
    98:  "{  | Boeing, (2017) |  |  |zu:0:A4P95YNT}",
    # 99 = OpenStreetMap contributors (website)
    # 100 = Brundl et al. (2009) — not found in Zotero
    # 101 = FEMA NRI Technical Documentation (report)
    # 102 = U.S. Census Bureau ACS (dataset)
    # 103 = CDC/ATSDR SVI (dataset)
    104: "{  | Hagberg et al., (2008) |  |  |zu:0:9YL5Q2UM}",
    105: "{  | Handy & Niemeier, (1997) |  |  |zu:0:58BKAUBP}",
    106: "{  | Zilske et al., (2011) |  |  |zu:0:HSZHFRJ8}",
    # 107 = Rivera-Royero & Jaller (2024) — not found in Zotero
    # 108 = worldpopulationreview (website)
    # 109 = Chapman university (website)
    110: "{  | McDonald, (2009) |  |  |zu:0:22HMKCIA}",
    111: "{  | Ranstam & Cook, (2018) |  |  |zu:0:WGEFH35B}",
    # 112 = Hastie (2017) book chapter — not found in Zotero
    # 113 = Garrison & Marble (1965) report — not found in Zotero
    114: "{  | Rodrigue, (2020) |  |  |zu:0:UINV5VWB}",
    # 115 = Mark Thomas (2022) technical memo — not found in Zotero
    116: "{  | Lam & Schuler, (1982) |  |  |zu:0:HFSP726G}",
    117: "{  | Scott et al., (2006) |  |  |zu:0:CJWVJSU3}",
    118: "{  | Aydin et al., (2018) |  |  |zu:0:5CI8PABK}",
    119: "{  | Latora & Marchiori, (2001) |  |  |zu:0:QBUQDK5K}",
    120: "{  | Mattsson & Jenelius, (2015) |  |  |zu:0:34QSTFHT}",
    121: "{  | Dehghani et al., (2014) |  |  |zu:0:QAA7VFVG}",
    122: "{  | Bell, (2000) |  |  |zu:0:J8FKTJQV}",
    123: "{  | Wang et al., (2017) |  |  |zu:0:UN9ZXR2X}",
    124: "{  | Snelder et al., (2012) |  |  |zu:0:PNR5FHDM}",
    125: "{  | Akbarzadeh et al., (2017) |  |  |zu:0:CHXNTUKQ}",
    126: "{  | Kermanshah & Derrible, (2017) |  |  |zu:0:AFHY8TLS}",
    127: "{  | Chang & Nojima, (2001) |  |  |zu:0:WB7TC875}",
    128: "{  | Taylor, (2008) |  |  |zu:0:PDN3N3ZB}",
    129: "{  | Hansen, (1959) |  |  |zu:0:5KIDY9UF}",
    130: "{  | Sohn, (2006) |  |  |zu:0:TA7992PK}",
    # 131 = Paez et al. (2012) — not found in Zotero
    132: "{  | Berdica, (2002) |  |  |zu:0:2NYL9SLV}",
    133: "{  | Luathep et al., (2011) |  |  |zu:0:TE5HCWKD}",
    134: "{  | Sullivan et al., (2010) |  |  |zu:0:R2CP4DC5}",
    135: "{  | Oliveira et al., (2016) |  |  |zu:0:BMGR7YBI}",
    136: "{  | Vodak et al., (2015) |  |  |zu:0:TCPYD74R}",
    137: "{  | Cats, (2016) |  |  |zu:0:7H3YKGPS}",
    138: "{  | Sakakibara et al., (2004) |  |  |zu:0:ASZRBHXL}",
    139: "{  | Ip & Wang, (2009) |  |  |zu:0:2PYRTK7K}",  # same as 23
    140: "{  | Sharov & Mikhailov, (2017) |  |  |zu:0:JWN7CA6H}",
    141: "{  | van Lint et al., (2008) |  |  |zu:0:3DBIDI4C}",
    142: "{  | Shariat-Mohaymany & Babaei, (2010) |  |  |zu:0:WVIHHWKX}",
    143: "{  | Chen et al., (1999) |  |  |zu:0:LY2RP6Y5}",
    144: "{  | Jenelius et al., (2006) |  |  |zu:0:W56FFXFY}",
    145: "{  | Khademi et al., (2015) |  |  |zu:0:6DJ53CM6}",
}

# References NOT found in Zotero that need to be added manually:
NOT_IN_ZOTERO = {
    3:   "DHS (2022) website — https://www.dhs.gov/natural-disasters",
    5:   "climate.org (2021) website",
    7:   "statista website",
    9:   "Meyer, Rowan, Savonis, Choate (2012) — AASHTO report on extreme weather & transportation",
    11:  "Jaller, González-Calderón, Yushimito, Sánchez-Díaz (2015) — Medellin infrastructure study",
    45:  "Damašvičius, Bacanin, Misra (2023) — IoES journal article",
    54:  "Stern & Sinuany-Stern (1989) — behavioural simulation urban evacuation",
    69:  "Alcadá-Almeida, Tralhão, Santos, Coutinho-Rodrigues (2009) — multiobjective emergency shelters",
    74:  "Lämmel, Grether, Nagel (2010) — time-dependent inundation microscopic evacuation",
    77:  "Coutinho-Rodrigues, Tralhão, Alcadá-Almeida (2012) — location-routing evacuation",
    89:  "McRae et al. (2016) — Omniscape / Conserving Nature's Stage (Nature Conservancy report)",
    90:  "McRae, Shah, Mohapatra (2013) — Circuitscape 4 User Guide",
    92:  "Schloss, Carroll, McRae (2022) — No-regrets pathways, Ecological Applications",
    94:  "Littlefield, Krosby, Michalak, Lawler (2019) — Connectivity for species on the move",
    96:  "California State Geoportal (2022) website",
    97:  "FEMA (2023) National Risk Index Map website",
    99:  "OpenStreetMap contributors (2023) website",
    100: "Brundl, Romang, Bischof, Rheinberger (2009) — risk concept Switzerland, NHESS",
    101: "FEMA (2023) National Risk Index Technical Documentation",
    102: "U.S. Census Bureau (2020) American Community Survey dataset",
    103: "CDC/ATSDR (2023) SVI Data dataset",
    107: "Rivera-Royero & Jaller (2024) — standardized spatial risk analysis (preprint?)",
    108: "worldpopulationreview.com website",
    109: "Chapman University website",
    112: "Hastie (2017) — Generalized additive models, book chapter in Routledge",
    113: "Garrison & Marble (1965) — prolegomenon to forecasting transportation (Northwestern report)",
    115: "Mark Thomas (2022) — Evacuation Technical Memorandum, Paradise Transportation Master Plan",
    131: "Páez, Scott, Morency (2012) — measuring accessibility, Journal of Transport Geography",
}
